name: "TogoDX human instance deployment: DX-server"
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - develop

jobs:
  deploy-dx-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: "Checkout app repo"
        uses: actions/checkout@v2
        with:
          repository: togodx/togodx-app
          fetch-depth: 1
          path: app
          ref: main

      - name: "Copy config.dx-server.json"
        run: |
          cp -f ./config/config.dx-server.json ./app/build/config.json

      - name: "Upload to S3 bucket: togodx-dev-production"
        uses: opspresso/action-s3-sync@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
          FROM_PATH: "./app/build"
          DEST_PATH: "s3://togodx-dx-server/"
          OPTIONS: "--delete --acl public-read --exclude 'README.md'"
