name: "TogoDX human instance production deployment"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: "Checkout app repo"
        uses: actions/checkout@v2
        with:
          repository: togodx/togodx-app
          fetch-depth: 1
          path: app
          ref: main

      - name: "Copy config.production.json"
        run: |
          cp -f ./config/config.production.json ./app/build/config.json

      - name: "Commit & Push changes to main"
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.ADMIN_TOKEN }}
          branch: main
          force: true

      - id: date
        run: echo "::set-output name=date::$(TZ=Asia/Tokyo date +'%Y%m%d-%H%M%S')"

      - uses: avakar/tag-and-release@v1
        with:
          tag_name: release-${{ steps.date.outputs.date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Upload to S3 bucket: togodx-production"
        uses: opspresso/action-s3-sync@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
          FROM_PATH: "./app/build"
          DEST_PATH: "s3://togodx-dx-server/"
          OPTIONS: "--delete --acl public-read --exclude 'README.md'"
